dictionaries:
  - en
  - en_GB

# Files to exclude
excluded_files:
  - "*.v"

# Words to exclude
excluded_words:
  - eprintln
  - mut
  - println
  - pub
  - fn
  - bool
  - typoci
  - u64
